### PR TITLE
Set winning strategy after _run!, in case _run! also sets winning_strategy

### PR DESCRIPTION
**Pull request by patrickmcguire**
Flips two lines to allow scopes authenticating from another without stepping on each other's toes. See https://github.com/hassox/warden/issues/143

### CODE REVIEW

**Comment by whithub** [comment]
I took a look at this and I'm not 100% sure with this chunk of code. @hassox do you mind taking a look? If you're okay with the change, I'm happy to take it from there.

**Comment by hassox** [comment]
I think this looks fine @whithub :D

**Comment by whithub** [comment]
@hassox For my own knowledge, is there any risk of calling `._run!` on strategy and then reassigning it the next line? Should I add a spec? Thanks!

**Comment by hassox** [comment]
@whithub I'm not entirely sure. It's been a long time. I would definitely recommend a spec!

**Pull request merged**
